image: alpine/edge
oauth: git.sr.ht/REPOSITORIES:RW git.sr.ht/PROFILE:RO
triggers:
  - action: email
    condition: failure
    to: Sebastian LaVine <mail@smlavine.com>
packages:
  - cmark
  - jo
  - jq
sources:
  - https://git.sr.ht/~smlavine/aurpackages
tasks:
  - convert-md-to-html: |
      # sourcehut renders markdown files with one heading level below what is
      # generated to html. So we have to adjust headings ourselves to make our
      # READMEs look the same as other markdown files rendered on sourcehut.
      set -o pipefail
      cmark aurpackages/README.md |
          sed -e 's:^<h5>:<h6>:' -e 's:</h5>$:</h6>:' \
              -e 's:^<h4>:<h5>:' -e 's:</h4>$:</h5>:' \
              -e 's:^<h3>:<h4>:' -e 's:</h3>$:</h4>:' \
              -e 's:^<h2>:<h3>:' -e 's:</h2>$:</h3>:' \
              -e 's:^<h1>:<h2>:' -e 's:</h1>$:</h2>:' |
          tee README.html
  - update-readmes: |
      set -o pipefail
      for r in catgirl-aur; do
          id="$(printf 'query { me { repository(name: "%s") { id } } }' "$r" |
              acurl -Ss -G --data-urlencode query@- https://git.sr.ht/query |
              jq '.data.me.repository.id')"
          jo -p variables[id]="$id" variables[readme]=@README.html query='
              mutation UpdateRepo($id: Int!, $readme: String!) {
                  updateRepository(id: $id, input: { readme: $readme }) { id }
              }' |
          acurl -Ss -d@- -H "Content-Type: application/json" \
              https://git.sr.ht/query
      done
