image: alpine/edge
oauth: git.sr.ht/REPOSITORIES:RW
triggers:
  - action: email
    condition: failure
    to: Sebastian LaVine <mail@smlavine.com>
packages:
  - cmark
  - jo
sources:
  - https://git.sr.ht/~smlavine/aurpackages
tasks:
  # In sr.ht/~smlavine/aurpackages, there are git repositories of AUR
  # packages that I maintain. I don't want to have a README.md in those
  # repositories, because their primary home is on aur.archlinux.org, but I
  # still want to show the project README on their git.sr.ht page. This
  # uploads the README for this repository to those repositories. This
  # GraphQL endpoint expects HTML, so we have to convert it here. Inline in
  # this script are repository IDs for each repository I upload the README to.
  # They are:
  #     ~smlavine/catgirl-aur (72346)
  - convert-md-to-html: |
      # sourcehut renders markdown files with one heading level below what is
      # generated to html. So we have to adjust headings ourselves to make our
      # READMEs look the same as other markdown files rendered on sourcehut.
      set -o pipefail
      cmark aurpackages/README.md |
          sed -e 's:^<h5>:<h6>:' -e 's:</h5>$:</h6>:' \
              -e 's:^<h4>:<h5>:' -e 's:</h4>$:</h5>:' \
              -e 's:^<h3>:<h4>:' -e 's:</h3>$:</h4>:' \
              -e 's:^<h2>:<h3>:' -e 's:</h2>$:</h3>:' \
              -e 's:^<h1>:<h2>:' -e 's:</h1>$:</h2>:' |
          tee README.html
  - generate-query: |
      set -o pipefail
      jo variables[id]=72346 variables[readme]=@README.html query='
          mutation UpdateRepo($id: Int!, $readme: String!) {
              updateRepository(id: $id, input: { readme: $readme }) { id }
          }' | tee query.graphql
  - send-query: |
      acurl -H "Content-Type: application/json" -d@query.graphql \
          https://git.sr.ht/query
